openapi: '3.0.3'
info:
  title: Example API
  version: '1.0.0'
paths:
  /api/session:
    get:
      tags: [Session]
      summary: check existence of session
      responses:
        204:
          description: exists a session
        401:
          description: unauthorized
    post:
      tags: [Session]
      summary: create session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  example: me@example.com
                password:
                  type: string
                  example: password
      responses:
        204:
          description: logged in
        400:
          description: wrong login information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wrong login information
    delete:
      tags: [Session]
      summary: delete sesion
      responses:
        204:
          description: logged out
  /api/users:
    get:
      tags: [User]
      summary: search users
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: John
      responses:
        200:
          description: search result
          content:
            application/json:
              schema:
                type: object
                required: [users]
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    post:
      tags: [User]
      summary: register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                  example: John Doe
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                type: object
                required: [user]
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        400:
          description: invalid parameters
          content:
            application/json:
              schema:
                type: object
                required: [errors]
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      required: [key, message]
                      properties:
                        key:
                          type: string
                          example: name
                        message:
                          type: string
                          example: Invalid characters included.
  /api/users/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: number
          example: 12345
    get:
      tags: [User]
      summary: get a user
      responses:
        200:
          description: found a user
          content:
            application/json:
              schema:
                type: object
                required: [user]
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        401:
          description: login required
        404:
          description: not found
    put:
      tags: [User]
      summary: update user information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
      responses:
        201:
          description: updated
          content:
            application/json:
              schema:
                type: object
                required: [user]
                properties:
                  user:
                    $ref: '#/components/schemas/User'
    delete:
      tags: [User]
      summary: unregister a user
      responses:
        204:
          description: deleted
        401:
          description: permission denied
        404:
          description: not found / already deleted
  /api/binary:
    get:
      tags: [Binary]
      summary: Binary
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                foo:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
components:
  schemas:
    User:
      type: object
      required: [id, name, birthday, unsupportedTypeProperty]
      properties:
        id:
          type: number
          example: 12345
        name:
          type: string
          example: John Doe
        birthday:
          type: string
          format: date
          nullable: true
        unsupportedTypeProperty:
          type: UnsupportedType
